require 'ast/iterators/cartesian_iterator'
require 'ast/iterators/dummy_iterator'
require 'ast/iterators/memory_table_scanner'
require 'ast/iterators/projector'
require 'ast/iterators/selector'
require 'ast/iterators/expression_evaluator'